<ips:template parameters="$action"/>
{{if $action['kind'] === \IPS\vssupport\ActionKind::Message}}
	<div class="ipsBox ticket-message {$action['classes']}">
		<div class="ipsBox__header i-padding-end_2"><span class="i-flex_91 message-author">{$action['initiator']}</span>{{if !empty($action['direct_link'])}}&nbsp;<a rel="external nofollow noopener noreferrer alternate" href="{$action['direct_link']}">{lang="link"}</a>{{endif}}<span class="i-font-size_-2 i-color_soft i-flex_00"><i class="fa-solid fa-clock"></i>&nbsp;{{$return .= \IPS\vssupport\format_local_date_time($action['created'])->html();}}</span></div>
		<div class="i-padding_2">{$action['text']|raw}</div>
	</div>
{{else}}
	<div class="i-padding-inline_2 i-color_soft i-flex i-gap_1">
		<span class="i-flex_91">
		{{switch($action['kind']): case \IPS\vssupport\ActionKind::PriorityChange:}}
			{lang="priority_changed_to"}&nbsp;{template="ticketLabel" location="global" group="tickets" params="'prio', $action['reference_id']"}
		{{break; case \IPS\vssupport\ActionKind::CategoryChange:}}
			{lang="category_changed_to"}&nbsp;{lang="ticket_category_{$action['reference_id']}_name"}
		{{break; case \IPS\vssupport\ActionKind::StatusChange:}}
			{lang="status_changed_to"}&nbsp;{template="ticketLabel" location="global" group="tickets" params="'status', $action['reference_id']"}
		{{break; case \IPS\vssupport\ActionKind::Assigned:}}
			{{if $action['reference_id']}}
				{lang="ticket_assigned_to"}&nbsp;{$action['assigned_to_name']}
			{{else}}
				{lang="ticket_unassigned"}
			{{endif}}
		{{break; case \IPS\vssupport\ActionKind::LockedChange:}}
			{lang="locked_changed_to_{$action['reference_id']}"}
		{{break; case \IPS\vssupport\ActionKind::UserDeleted:}}
			{lang="ticket_issuer_deleted"}
		{{break; case \IPS\vssupport\ActionKind::UserMerged:}}
			{lang="ticket_issuer_merged"}
		{{break; case \IPS\vssupport\ActionKind::UserValidated:}}
			{lang="ticket_issuer_validated"}
		{{break; case \IPS\vssupport\ActionKind::UserEmailChanged:}}
			{lang="ticket_issuer_email_changed"}
		{{break; case \IPS\vssupport\ActionKind::UserNameChanged:}}
			{lang="ticket_issuer_name_changed"}
		{{break; default:}}
			Action: {$action['kind']} {$action['reference_id']}
		{{endswitch}}
		</span>
		{template="actionContextInfo" group="tickets" params="$action"}
	</div>
{{endif}}