<ips:template parameters="$action"/>
{{if $action['kind'] === \IPS\vssupport\ActionKind::Message}}
	<div class="ipsBox{{if $action['flags'] & \IPS\vssupport\MessageFlags::Internal}} internal-note{{endif}}">
		<div class="ipsBox__header">{$action['initiator']}</div>
		<div class="i-padding_2">{$action['text']|raw}</div>
		<div class="i-font-size_-2 i-color_soft i-padding_2 i-padding-top_0 message-time"><i class="fa-solid fa-clock"></i>&nbsp;{$action['created']}</div>
	</div>
{{else}}
	<div class="ipsBox i-padding_2">
	{{switch($action['kind']): case \IPS\vssupport\ActionKind::PriorityChange:}}
		{lang="priority_changed_to"}&nbsp;{template="priorityLabel" location="global" group="tickets" params="$action['reference_id']"}
	{{break; case \IPS\vssupport\ActionKind::CategoryChange:}}
		{lang="category_changed_to"}&nbsp;{lang="ticket_cat_{$action['name_key']}_name"}
	{{break; case \IPS\vssupport\ActionKind::StatusChange:}}
		{lang="status_changed_to"}&nbsp;{lang="ticket_status_{$action['name_key']}_name"}
	{{break; case \IPS\vssupport\ActionKind::Assigned:}}
		{{if $action['reference_id']}}
			{lang="ticket_assigned_to"}&nbsp;{$action['assigned_to_name']}
		{{else}}
			{lang="ticket_unassigned"}
		{{endif}}
	{{break; case \IPS\vssupport\ActionKind::LockedChange:}}
		{lang="locked_changed_to_{$action['reference_id']}"}
	{{break; case \IPS\vssupport\ActionKind::UserDeleted:}}
		{lang="ticket_issuer_deleted"}
	{{break; case \IPS\vssupport\ActionKind::UserMerged:}}
		{lang="ticket_issuer_merged"}
	{{break; case \IPS\vssupport\ActionKind::UserValidated:}}
		{lang="ticket_issuer_validated"}
	{{break; case \IPS\vssupport\ActionKind::UserEmailChanged:}}
		{lang="ticket_issuer_email_changed"}
	{{break; case \IPS\vssupport\ActionKind::UserNameChanged:}}
		{lang="ticket_issuer_name_changed"}
	{{break; default:}}
		Action: {$action['kind']} {$action['reference_id']}
	{{endswitch}}
		{template="actionContextInfo" group="tickets" params="$action"}
	</div>
{{endif}}