<?php

$lang = array(
	'__app_vssupport'	=> 'VS Support',
	'menutab__vssupport' => 'VS Support',
	'menutab__vssupport_icon' => 'comments',
	'menu__vssupport_tickets' => 'Tickets',
	'menu__vssupport_tickets_tickets' => 'Ticket List',
	'module__vssupport_tickets' => 'Tickets',
	'frontnavigation_vssupport' => 'Support',
	'tickets' => 'Tickets',
	'ticket' => 'Ticket',
	'ticket_submit' => 'Submit Ticket',
	'ticket_create' => 'New Ticket',
	'ticket_lock' => 'Lock Ticket',
	'ticket_lock_desc' => 'Locking a ticket restricts conversation to staff member only and prevents reopening by the issuer.',
	'ticket_locked' => 'This Ticket has been locked.',
	'locked_changed_to_0' => 'Ticket has been Unlocked',
	'locked_changed_to_1' => 'Ticket has been Locked',
	'ticket_issuer_deleted' => 'The issuer of this ticket was deleted. Name and notification email will be kept.',
	'ticket_issuer_merged' => 'The issuer of this ticket was merged into another user. The ticket issuer has been adjusted.',
	'ticket_issuer_validated' => 'A user with the same email as the issuer of this ticket has completed registration. This ticket has been merged into that user.',
	'ticket_issuer_email_changed' => 'The ticket issuer changed their email. The notification email has been adjusted.',
	'ticket_issuer_name_changed' => 'The issuer of this thicket changed their display name.',
	'my_tickets' => 'My Tickets',
	'message_add' => 'Add Message',
	'menu__vssupport_tickets_categories' => 'Manage Categories',
	'category' => 'Category',
	'category_add' => 'Add new Category',
	'category_edit' => 'Edit Category',
	'category_changed_to' => 'Category has been changed to',
	'name_key_desc' => 'The <code>name_key</code> used when displaying this category. The final translation key for this category\'s name will be composed as <code>ticket_cat_name_{name_key}</code>.',
	'priority' => 'Priority',
	'priority_changed_to' => 'Priority has been changed to',
	'assigned_to' => 'Assigned To',
	'assign_to' => 'Assign To',
	'ticket_assigned_to' => 'Ticket has been assigned to',
	'ticket_unassigned' => 'Ticket assignment has been removed',
	'text' => 'Text',
	'editor__vssupport_TicketText' => 'Ticket Creation',
	'respond_internal' => 'Add as Internal Note',
	'respond_public' => 'Respond',
	'dont_change' => "Don't change",
	'current' => 'Current',
	'users_invoices' => "%s's Invoices",
	'users_purchases' => "%s's Purchases",

	'r__tickets' => 'Can access Tickets?',
	'r__tickets_manage' => 'Can manage Tickets?',
	'r__categories_manage' => 'Can manage Categories?',

	'ticket_prio_name_-2' => 'Backlog',
	'ticket_prio_name_-1' => 'Below Average',
	'ticket_prio_name_0'  => 'Normal',
	'ticket_prio_name_1'  => 'Important',
	'ticket_prio_name_2'  => 'Urgent',

	'ticket_cat_name_cat1' => 'Category 1',
	'ticket_cat_name_cat2' => 'Category 2',
);
