<?php

$lang = array(
	'__app_vssupport'	=> 'VS Support',
	'menutab__vssupport' => 'VS Support',
	'menutab__vssupport_icon' => 'comments',
	'menu__vssupport_tickets' => 'Tickets',
	'menu__vssupport_tickets_tickets' => 'Ticket List',
	'module__vssupport_tickets' => 'Tickets',
	'frontnavigation_vssupport' => 'Support',
	'tickets' => 'Tickets',
	'ticket' => 'Ticket',
	'ticket_submit' => 'Submit Ticket',
	'ticket_create' => 'New Ticket',
	'ticket_lock' => 'Lock Ticket',
	'ticket_lock_desc' => 'Locking a ticket restricts conversation to staff member only and prevents reopening by the issuer.',
	'ticket_locked' => 'This Ticket has been locked.',
	'locked_changed_to_0' => 'Ticket has been Unlocked',
	'locked_changed_to_1' => 'Ticket has been Locked',
	'ticket_issuer_deleted' => 'The issuer of this ticket was deleted. Name and notification email will be kept.',
	'ticket_issuer_merged' => 'The issuer of this ticket was merged into another user. The ticket issuer has been adjusted.',
	'ticket_issuer_validated' => 'A user with the same email as the issuer of this ticket has completed registration. This ticket has been merged into that user.',
	'ticket_issuer_email_changed' => 'The ticket issuer changed their email. The notification email has been adjusted.',
	'ticket_issuer_name_changed' => 'The issuer of this thicket changed their display name.',
	'my_tickets' => 'My Tickets',
	'message_add' => 'Add Message',
	'ticked_considered_closed_notice' => 'This ticket is considered to be closed, responding will reopen the ticket.',
	'menu__vssupport_tickets_categories' => 'Manage Categories',
	'category' => 'Category',
	'category_add' => 'Add new Category',
	'category_edit' => 'Edit Category',
	'category_changed_to' => 'Category has been changed to',
	'category_name_key' => 'name_key',
	'category_name_key_desc' => 'The <code>name_key</code> used when displaying this category. The final translation key for this category\'s name will be composed as <code>ticket_cat_{name_key}_name</code>.',
	'menu__vssupport_tickets_stati' => 'Manage Stati',
	'status' => 'Status',
	'status_add' => 'Add new Status',
	'status_edit' => 'Edit Status',
	'status_changed_to' => 'Status has been changed to',
	'stati' => 'Stati',
	'status_name_key' => 'name_key',
	'status_name_key_desc' => 'The <code>name_key</code> used when displaying this status. The final translation key for this status\'s name will be composed as <code>ticket_status_{name_key}_name</code>.',
	'priority' => 'Priority',
	'priority_changed_to' => 'Priority has been changed to',
	'assigned_to' => 'Assigned To',
	'assign_to' => 'Assign To',
	'ticket_assigned_to' => 'Ticket has been assigned to',
	'ticket_unassigned' => 'Ticket assignment has been removed',
	'text' => 'Text',
	'editor__vssupport_TicketText' => 'Ticket Creation',
	'respond_internal' => 'Add as Internal Note',
	'respond_public' => 'Respond',
	'dont_change' => "Don't change",
	'current' => 'Current',
	'users_invoices' => "%s's Invoices",
	'users_purchases' => "%s's Purchases",

	'r__tickets' => 'Can access Tickets?',
	'r__tickets_manage' => 'Can manage Tickets?',
	'r__categories_manage' => 'Can manage Categories?',
	'r__stati_manage' => 'Can manage Stati?',

	'ticket_prio_-2_name' => 'Backlog',
	'ticket_prio_-1_name' => 'Below Average',
	'ticket_prio_0_name'  => 'Normal',
	'ticket_prio_1_name'  => 'Important',
	'ticket_prio_2_name'  => 'Urgent',

	'ticket_cat_cat1_name' => 'Category 1',
	'ticket_cat_cat2_name' => 'Category 2',

	'ticket_status_open_name' => 'Open',
	'ticket_status_processing_name' => 'In Progress',
	'ticket_status_halted_name' => 'Halted',
	'ticket_status_completed_name' => 'Completed',
	'ticket_status_wontfix_name' => "Won't Fix",
	'ticket_status_custom_name' => "Custom Status",
);
