<ips:template parameters="$tickets"/>
<div style="text-align: right">
	{{$createLink = \IPS\Http\Url::internal('app=vssupport&module=tickets&controller=tickets&do=create', seoTemplate: 'tickets_create');}}
	{template="button" app="core" group="forms" location="global" params="'ticket_create', 'link', $createLink, 'ipsButton ipsButton--primary', ['tabindex' => 1, 'accesskey' => 'c']"}
</div>
<div class="i-flex i-flex-direction_column i-gap_1">
	{{foreach $tickets as $ticket}}
		<a class="ipsBox i-padding_2" href="{url="app=vssupport&module=tickets&controller=tickets&do=view&hash={$ticket['hash']}" seoTemplate="tickets_view_hash"}">
			<h3>{template="priorityLabel" location="global" group="tickets" params="$ticket['priority']"}{{if $ticket['flags'] & \IPS\vssupport\TicketFlags::Locked}}&nbsp;<i class="fa-solid fa-lock"></i>{{endif}} {$ticket['subject']}</h3>
			<h3>{$ticket['created']}</h3>
		</a>
	{{endforeach}}
</div>