<ips:template parameters="$ticket, $messages"/>
<h2 class="ipsTitle ipsTitle--h2">{lang="ticket"} #{$ticket['id']} - {lang="ticket_cat_name_{$ticket['category']}"} - <span class="prio-label prio-{$ticket['priority']}">{lang="ticket_prio_name_{$ticket['priority']}"}</span> {$ticket['subject']}</h2>
<h3 class="ipsTitle">{$ticket['user_name']} <span class="i-color_soft">started <i class="fa-solid fa-clock"></i>&nbsp;{$ticket['created']}</span></h3>
<div style="display: flex; flex-direction: column; gap: 1em;">
	{{foreach $messages as $message}}
		{template="message" location="global" group="tickets" params="$message"}
	{{endforeach}}
</div>