<ips:template parameters="$assignedAndOpen, $email" />
<br />
{$email->language->addToStack('mail_part__you_currently_have_n_open_tickets', options: ['pluralize' => [count($assignedAndOpen)]])}
<br/>
{{foreach $assignedAndOpen as $ticket}}
<br/>
<h3><a href="{url="app=vssupport&module=tickets&controller=tickets&do=view&id={$ticket['id']}" base:"admin"}">{$ticket['subject']}</a>&nbsp;<small>#{$ticket['id']}</small></h3>
<p>
{$email->language->addToStack('mail_part__ticket_description', options: ['sprintf' => [
	$ticket['created'],
	$email->language->addToStack('ticket_status_'.$ticket['status'].'_name', options: ['escape' => 1]),
	$email->language->addToStack('ticket_cat_'.$ticket['category'].'_name', options: ['escape' => 1]),
	$email->language->addToStack('ticket_prio_'.$ticket['priority'].'_name', options: ['escape' => 1]),
]])}
</p>
{{endforeach}}

<br /><br />
{$email->language->addToStack('mail_part__do_not_respond_to_this_email')}
<br /><br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>