<ips:template parameters="$ticketId, $ticketHash, $messageTextHtml, $initiatorName, $email" />
{{$ticketLink = \IPS\Http\Url::internal("app=vssupport&module=tickets&controller=tickets&do=view&hash={$ticketHash}", base: "front", seoTemplate: "tickets_view_hash");}}
<br />
{$email->language->addToStack('mail_part__initiator_responded_to_ticket', options: ['htmlsprintf' => [$initiatorName, $ticketLink, $ticketId]])}
<br />
<br />
<table width='100%' cellpadding='15' cellspacing='0' border='0'>
	<tr><td dir='{dir}'>{$messageTextHtml|raw}</td></tr>
</table>
<br />
<small>{$email->language->addToStack('mail_part__here_is_the_link_to_ticket_if_not_recognized')}
<br />
<a href="$ticketLink"><code>{$ticketLink}</code></a></small>
<br /><br />
{$email->language->addToStack('mail_part__do_not_respond_to_this_email')}
<br /><br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>