<ips:template parameters="$table"/>
<div id="ticket-list-wrapper" style="overflow-y: auto;">
	{$table|raw}
</div>
<style>
	#ticket-list-wrapper tr>:first-child {
		min-width: 45ch;
	}
</style>
<script>
	// middle click to open in new tab
	document.getElementById('ticket-list-wrapper').getElementsByTagName('table')[0].addEventListener("mousedown", e => {
		if(e.which !== 2) return;
		e.preventDefault();

		let row = e.target;
		while(row.nodeName !== 'TR') {
			row = row.parentElement;
			if(!row) return;
		}

		const anchorEl = row.lastElementChild.getElementsByTagName('a')[0];
		open(anchorEl.href, '_blank', 'noopener');
	})
</script>