<ips:template parameters="$ticket, $actions, $form, $extraBlocks, $sortDir"/>
<h2 class="ipsTitle ipsTitle--h2 i-flex"><span>{lang="ticket"} #{$ticket['id']} - {$ticket['subject']}</span><button id="change-history-sort" style="align-self: flex-start; margin-left: auto;" class="ipsButton i-padding_1 i-font-size_3" title="{lang='change_history_direction'}" click="javascript:void(0)"><i class="fa fa-sort-numeric-{$sortDir}"></i></button></h2>
<h3 class="ipsTitle ipsTitle--h3">{lang="ticket_category_{$ticket['category']}_name"} {template="priorityLabel" location="global" group="tickets" params="$ticket['priority']"}, {lang="ticket_status_{$ticket['status']}_name"}{{if $ticket['assigned_to']}}, {lang="assigned_to"}:&nbsp;{$ticket['assigned_to_name']}{{endif}}{{if $ticket['flags'] & \IPS\vssupport\TicketFlags::Locked}}&nbsp;<i class="fa-solid fa-lock"></i>{{endif}}</h3>
<h4 class="ipsTitle ipsTitle--h4">{$ticket['issuer_name']} - {$ticket['issuer_email']} <span class="i-color_soft">started <i class="fa-solid fa-clock"></i>&nbsp;{$ticket['created']}</span></h4>
<div id="tick-main-wrap">
	<div id="tick-hist-wrap" style="display: flex; flex-direction: column; gap: 1em;">
		{{if $sortDir === 'asc'}}
			{{foreach $actions as $action}}
				{template="action" location="global" group="tickets" params="$action"}
			{{endforeach}}
			{$form|raw}
		{{else}}
			{$form|raw}
			{{foreach $actions as $action}}
				{template="action" location="global" group="tickets" params="$action"}
			{{endforeach}}
		{{endif}}
	</div>
	<div id="extra-blocks-container">
		{{foreach $extraBlocks as $extra}}
			{$extra|raw}
		{{endforeach}}
	</div>
</div>
<script lang="text/javascript">
{
	let histSortDir = '{$sortDir}';
	const histContainer = document.getElementById('tick-hist-wrap');
	const changeSortBtn = document.getElementById('change-history-sort');
	changeSortBtn.addEventListener('click', () => {
		histSortDir = histSortDir === 'asc' ? 'desc' : 'asc';
		changeSortBtn.firstElementChild.classList.toggle('fa-sort-numeric-asc', histSortDir === 'asc')
		changeSortBtn.firstElementChild.classList.toggle('fa-sort-numeric-desc', histSortDir !== 'asc')
		histContainer.replaceChildren(...Array.from(histContainer.children).reverse());
		ips.utils.cookie.set('ticketSort', histSortDir, true);
	})
	if(histSortDir === 'asc') {
		//TODO(Rennorb) @ux: only scroll if previously read
		document.getElementById('reply-form').scrollIntoView({ behavior: "instant", block: "end" });
	}
}
</script>