<ips:template parameters="$ticket, $messages, $form"/>
<h2 class="ipsTitle ipsTitle--h2">{lang="ticket"} #{$ticket['id']} - {$ticket['subject']}</h2>
<h3 class="ipsTitle ipsTitle--h3">{lang="ticket_cat_name_{$ticket['category']}"} <span class="prio-label prio-{$ticket['priority']}">{lang="ticket_prio_name_{$ticket['priority']}"}</span>{{if $ticket['flags'] & \IPS\vssupport\TicketFlags::Locked}} {lang="locked"}{{endif}}</h3>
<h4 class="ipsTitle ipsTitle--h4">{$ticket['user_name']} - {$ticket['user_email']} <span class="i-color_soft">started <i class="fa-solid fa-clock"></i>&nbsp;{$ticket['created']}</span></h4>
<div style="display: flex; flex-direction: column; gap: 1em;">
	{{foreach $messages as $message}}
		{template="message" location="global" group="tickets" params="$message"}
	{{endforeach}}
	{$form|raw}
</div>